### ISSUE TITLE
Error: INTERNAL ERROR: missing context with id = 41

### ISSUE THREAD

**Issue by zhiweijie** [intergalacticalvariable/reader#11]
According to the installation instructions, after deployment, the website crashed a few times with an error.

Error: INTERNAL ERROR: missing context with id = 41
    at assert (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/util/assert.js:18:15)
    at FrameManager.executionContextById (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/FrameManager.js:202:32)
    at #onBindingCalled (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Page.js:643:44)
    at /app/node_modules/puppeteer-core/lib/cjs/third_party/mitt/mitt.js:62:7
    at Array.map (<anonymous>)
    at Object.emit (/app/node_modules/puppeteer-core/lib/cjs/third_party/mitt/mitt.js:61:20)
    at CdpCDPSession.emit (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/EventEmitter.js:83:23)
    at CdpCDPSession._onMessage (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/CDPSession.js:82:18)
    at Connection.onMessage (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Connection.js:133:25)
    at Immediate.<anonymous> (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/node/NodeWebSocketTransport.js:43:36)

Node.js v18.20.4

**Comment by ViktorJJF** [comment]
same here

2024-11-15 17:06:57 Readability output not sufficient, using original HTML
2024-11-15 17:06:57 /app/node_modules/puppeteer-core/lib/cjs/puppeteer/util/assert.js:18
2024-11-15 17:06:57         throw new Error(message);
2024-11-15 17:06:57               ^
2024-11-15 17:06:57 
2024-11-15 17:06:57 Error: INTERNAL ERROR: missing context with id = 11
2024-11-15 17:06:57     at assert (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/util/assert.js:18:15)
2024-11-15 17:06:57     at FrameManager.executionContextById (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/FrameManager.js:202:32)
2024-11-15 17:06:57     at #onBindingCalled (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Page.js:643:44)
2024-11-15 17:06:57     at /app/node_modules/puppeteer-core/lib/cjs/third_party/mitt/mitt.js:62:7
2024-11-15 17:06:57     at Array.map (<anonymous>)
2024-11-15 17:06:57     at Object.emit (/app/node_modules/puppeteer-core/lib/cjs/third_party/mitt/mitt.js:61:20)
2024-11-15 17:06:57     at CdpCDPSession.emit (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/EventEmitter.js:83:23)
2024-11-15 17:06:57     at CdpCDPSession._onMessage (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/CDPSession.js:82:18)
2024-11-15 17:06:57     at Connection.onMessage (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Connection.js:133:25)
2024-11-15 17:06:57     at Immediate.<anonymous> (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/node/NodeWebSocketTransport.js:43:36)

**Comment by printharsh** [comment]
+1 broken for me too
